### ISSUE TITLE
div class search?

### ISSUE THREAD

**Issue by KrijnHoetmer** [xxdaniquee/the-client-website#1]
Zie m'n opmerking van net :) Hier is een specifieker element voor: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/search

https://github.com/xxdaniquee/the-client-website/blob/610c7995fbc051a2e1d48e6cd8e9fe37c29ac58a/index.html#L32C14-L41

**Comment by xxdaniquee** [comment]
Deze div heb ik aangepast naar een search element
