### ISSUE TITLE
Divitis :)

### ISSUE THREAD

**Issue by KrijnHoetmer** [xxdaniquee/the-client-website#2]
Ook waar we het over hadden; kijk naar articles & sections: https://css-tricks.com/how-to-section-your-html/

https://github.com/xxdaniquee/the-client-website/blob/610c7995fbc051a2e1d48e6cd8e9fe37c29ac58a/index.html#L43-L56

**Comment by xxdaniquee** [comment]
De content onderdelen staan nu in een article element
